apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090 
  isDefault: true
  access: proxy
  editable: true
- name: InfluxDB
  type: influxdb
  access: proxy
  user: admin
  url: http://influxdb:8086
  jsonData:
    dbName: perfomance_db
    httpMode: GET
  secureJsonData:
    password: influx
