{
 "title": "Perfomance dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "k6_datasource", "label": "K6 Data Source", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "K6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "COUNT REQUESTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "MIN REQUEST DURATION | MS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT min(value) FROM \"http_req_duration\" WHERE value > 0 AND $timeFilter"
    }
   ]
  },
  {
   "title": "MED REQUEST DURATION | MS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT median(value) FROM \"http_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "MAX REQUEST DURATION | MS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(value) FROM \"http_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P(95) REQUEST DURATION | MS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(value) FROM \"http_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P(95) REQUEST DURATION | MS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT percentile(value, 95) FROM \"http_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Virtual users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "Active VUs",
     "query": "SELECT sum(\"value\") FROM \"vus\" WHERE $timeFilter GROUP BY time(1s) fill(none)"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "alias": "Requests per Second",
     "query": "SELECT sum(\"value\") FROM \"http_reqs\" WHERE $timeFilter GROUP BY time(1s) fill(null)"
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "alias": "Num Errors",
     "query": "SELECT count(\"value\") \nFROM \"http_reqs\"\nWHERE (\"status\" = '500' or \"status\" = '0') \n  AND $timeFilter \nGROUP BY time($__interval) \nfill(none)"
    }
   ]
  },
  {
   "title": "REQUEST DURATION | sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "SELECT value * 0.001  FROM \"http_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Checks Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "checks",
     "query": "SELECT sum(\"value\") FROM \"autogen\".\"checks\" WHERE $timeFilter GROUP BY time($__interval), \"check\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "URLs and latencies",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "SELECT count(\"value\"), min(\"value\"), median(\"value\"), max(\"value\"), mean(\"value\"), percentile(\"value\", 95) FROM \"autogen\"./^http_req_duration$/ WHERE $timeFilter GROUP BY \"name\""
    }
   ]
  },
  {
   "title": "HTTP status table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"http_reqs\" where $timeFilter group by status, method, \"name\""
    }
   ]
  },
  {
   "title": "HTTP fail table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"http_reqs\" WHERE (\"status\" != '200' AND \"status\" != '201' AND \"status\" != '302' AND \"status\" != '301' ) AND $timeFilter group by status, method, \"name\""
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU USAGE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{instance=~\"$host:9100\",mode=\"idle\"}[1m])) * 100)"
      }
     ]
    },
    {
     "title": "MEMORY USAGE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{instance=~\"$host:9100\"} - node_memory_MemFree_bytes{instance=~\"$host:9100\"} - (node_memory_Cached_bytes{instance=~\"$host:9100\"} + node_memory_Buffers_bytes{instance=~\"$host:9100\"})\n) / (node_memory_MemTotal_bytes{instance=~\"$host:9100\"}) * 100"
      }
     ]
    },
    {
     "title": "HDD USAGE | /",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100-((node_filesystem_avail_bytes{instance=~\"$host:.*?\",mountpoint=\"/\",device!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$host:.*?\",mountpoint=\"/\",device!=\"rootfs\"})",
       "legendFormat": "$host"
      }
     ]
    },
    {
     "title": "NETWORK | MB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$host:9100\",}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "W/R DISK | MB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$host:9100\", device=\"sda\"}) / 1024",
       "legendFormat": "Read disk"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$host:9100\", device=\"sda\"}) / 1024",
       "legendFormat": "Write dist"
      }
     ]
    }
   ]
  },
  {
   "title": "PG_EXPORTER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Max connections",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_connections{instance=~\"$pg_host:9187\"}"
      }
     ]
    },
    {
     "title": "Connections used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_database_numbackends{instance=~\"$pg_host:9187\"})/max(pg_settings_max_connections{instance=~\"$pg_host:9187\"})"
      }
     ]
    },
    {
     "title": "Total active users",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{state=\"active\", instance=~\"$pg_host:9187\"})",
       "legendFormat": "$pg_host"
      }
     ]
    },
    {
     "title": "Total idle users",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 15, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{state=\"idle\",instance=~\"$pg_host:9187\"})",
       "legendFormat": "$pg_host"
      }
     ]
    },
    {
     "title": "Total active users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{state=\"active\", instance=~\"$pg_host:9187\"})",
       "legendFormat": "$pg_host"
      }
     ]
    },
    {
     "title": "Total idle users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{state=\"idle\",instance=~\"$pg_host:9187\"})",
       "legendFormat": "$pg_host"
      }
     ]
    },
    {
     "title": "CPU USAGE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{instance=~\"$pg_host:9100\",mode=\"idle\"}[1m])) * 100)"
      }
     ]
    },
    {
     "title": "MEMORY USAGE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{instance=~\"$pg_host:9100\"} - node_memory_MemFree_bytes{instance=~\"$pg_host:9100\"} - (node_memory_Cached_bytes{instance=~\"$pg_host:9100\"} + node_memory_Buffers_bytes{instance=~\"$pg_host:9100\"})\n) / (node_memory_MemTotal_bytes{instance=~\"$pg_host:9100\"}) * 100"
      }
     ]
    },
    {
     "title": "HDD USAGE | /",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100-((node_filesystem_avail_bytes{instance=~\"$pg_host:.*?\",mountpoint=\"/\",device!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$pg_host:.*?\",mountpoint=\"/\",device!=\"rootfs\"})",
       "legendFormat": "$host"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum((rate(pg_stat_database_xact_commit{instance=~\"$pg_host:9187\"})))"
      },
      {
       "expr": "sum ((rate(pg_stat_database_xact_rollback{instance=~\"$pg_host:9187\"})))"
      }
     ]
    }
   ]
  }
 ]
}